### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dimaip** [psmb/Psmb.FlatNav#1]
- [x] Filtering & search
- [x] Code quality and clean up
- [x] Reload on dimension or workspace change
- [x] Spinner shown in inspector (wrong node merge)

Please help and provide PRs if you use the package!
